dataset:
  filepath: "Grand Est/data_train.parquet"
  fill_missing_pixels: true
  input_columns:
    - "evspsblpotAdjust-FAO"
    - "evspsblpotAdjust-Hg0175"
    - "hussAdjust"
    - "prtotAdjust_max"
    - "prtotAdjust_sum"
    - "prtotAdjust_avg"
    - "rldsAdjust"
    - "rsdsAdjust"
    - "tasAdjust"
    - "tasmaxAdjust"
    - "tasminAdjust"
  target_column: "swi_u"
  map_dimensions: (37, 44)
  x_dim_column: null
  y_dim_column: null
  starting_year: 2022
  starting_month: 5

evaluation:
  trajectories_path: "Outputs/inference_grand_est_test.npy"
  saving_path: "Outputs/evaluation_metrics_grand_est_test"